/*
package com.makibeans.model;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AttributeTemplateTest {

    private AttributeTemplate attributeTemplate;

    @BeforeEach
    void setUp() {
        attributeTemplate = new AttributeTemplate("Origin");
    }

    @AfterEach
    void tearDown() {
        attributeTemplate = null;
    }

    // Constructor Tests
    @Test
    void shouldReturnCorrectNameFromConstructor() {
        assertEquals("Origin", attributeTemplate.getName(), "The name should be set correctly by the constructor");
    }

    // Setter Tests
    @Test
    void shouldSetNameSuccessfully() {
        attributeTemplate.setName("Flavor");
        assertEquals("Flavor", attributeTemplate.getName(), "The name should be set correctly via setter");
    }

    // Getter Tests
    @Test
    void shouldReturnCorrectNameWhenRequested() {
        assertEquals("Origin", attributeTemplate.getName(), "The name should be 'Origin' as initialized");
    }

    // toString Method Test
    @Test
    void shouldReturnCorrectToString() {
        String expected = "AttributeTemplate(id=null, name=Origin)"; // 'id' is null because it is autogenerated
        assertEquals(expected, attributeTemplate.toString(), "The toString method should return the correct string representation of the object");
    }
}
*/
