package com.makibeans.model;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AttributeTemplateTest {

    private AttributeTemplate attributeTemplate;

    @BeforeEach
    void setUp() {
        attributeTemplate = new AttributeTemplate("Origin");
    }

    @AfterEach
    void tearDown() {
        attributeTemplate = null;
    }

    @Test
    void shouldReturnNotNullWhenCreated() {
        assertNotNull(attributeTemplate, "The attribute template should not be null after creation");
    }

    @Test
    void shouldReturnCorrectNameFromConstructor() {
        assertEquals("Origin", attributeTemplate.getName(), "The name should be set correctly by the constructor");
    }

    @Test
    void shouldSetNameSuccessfully() {
        attributeTemplate.setName("Flavor");
        assertEquals("Flavor", attributeTemplate.getName(), "The name should be set correctly");
    }

    @Test
    void shouldReturnCorrectName() {
        assertEquals("Origin", attributeTemplate.getName(), "The name should be 'Origin' as initialized");
    }

    @Test
    void shouldReturnCorrectToString() {
        String expected = "AttributeTemplate{id=null, name='Origin'}"; // Note: 'id' is null because it is autogenerated
        assertEquals(expected, attributeTemplate.toString(), "The toString method should return the correct format");
    }
}
