/*
package com.makibeans.model;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AttributeValueTest {

    private AttributeValue attributeValue;

    @BeforeEach
    void setUp() {
        attributeValue = new AttributeValue(new AttributeTemplate("Size"), "Large");
    }

    @AfterEach
    void tearDown() {
        attributeValue = null;
    }

    // Constructor Tests
    @Test
    void shouldReturnNotNullWhenCreated() {
        assertNotNull(attributeValue, "The attribute value should not be null after creation");
    }

    @Test
    void shouldReturnCorrectAttributeTemplateFromConstructor() {
        assertEquals("Size", attributeValue.getAttributeTemplate().getName(), "The attribute template name should be correctly initialized by the constructor");
    }

    @Test
    void shouldReturnCorrectValueFromConstructor() {
        assertEquals("Large", attributeValue.getValue(), "The value should be correctly initialized by the constructor");
    }

    // Setter Tests
    @Test
    void shouldSetAttributeValueSuccessfully() {
        attributeValue.setValue("Small");
        assertEquals("Small", attributeValue.getValue(), "The value should be set correctly via setter");
    }

    // toString Method Test
    @Test
    void shouldReturnCorrectToString() {
        String expected = "AttributeValue(id=null, value=Large)"; // 'id' is null because it is autogenerated
        assertEquals(expected, attributeValue.toString(), "The toString method should return the correct format");
    }
}*/
