/*
package com.makibeans.model;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class SizeTest {

    private Size size;

    @BeforeEach
    void setUp() {
        size = new Size("Large");
        size.setName("Large");
    }

    @AfterEach
    void tearDown() {
        size = null;
    }

    // Constructor Tests
    @Test
    void shouldReturnNotNullWhenCreated() {
        assertNotNull(size, "The size object should not be null after creation");
    }

    // Setter Tests
    @Test
    void shouldSetSizeNameSuccessfully() {
        size.setName("Medium");
        assertEquals("Medium", size.getName(), "The size description should be updated correctly via setter");
    }

    // Getter Tests
    @Test
    void shouldReturnCorrectIdWhenRequested() {
        assertNull(size.getId(), "The id should be null because it's autogenerated and not yet persisted");
    }

    @Test
    void shouldReturnCorrectSizeNameWhenRequested() {
        assertEquals("Large", size.getName(), "The size name should be 'Large' as initialized");
    }

    // toString Method Test
    @Test
    void shouldReturnCorrectToString() {
        String expected = "Size(id=null, name=Large)";
        assertEquals(expected, size.toString(), "The toString method should return the correct format");
    }
}
*/
